### PR TITLE
add single checkbox comp

### PR DESCRIPTION
**Pull request by kingy04**
Adds a checkbox component

### CODE REVIEW

**Comment by BrockReece** [comment]
Which branch are we using for the client onboarding project?
I think going forward, everything released should only depend on tagged versions of packages already merged into master so we don't suffer from divergence and we can also depend on SemVer conventions.

**Comment by kingy04** [comment]
Onboarding uses master.. however, the yarn build includes my changes from this branch

**Comment by BrockReece** [comment]
Master is still based on Vue1 though?
And if the yarn.lock wasn't built from the package.json that sounds really risky.
If I refer to the package.json before I perform a fix on that particular branch, the branches would diverge without me even knowing.

**Comment by kingy04** [comment]
oops, I used the vue2 branch not master, i made the changes to the node modules folder in onboarding, and it was built from there, not ideal i know however the risk was low in this case as the project would still work fine without the checkbox component. Thanks

**Pull request merged**
